### ISSUE TITLE
Error running hillclimbing

### ISSUE THREAD

**Issue by isidoramorel** [sandain/ecosim#3]
Hi! I am trying to run ecosym from a Linux system without a graphical interphase and I keep running into the same error with hillclimbing. This is the command I used: `java -jar ~/ecotype/ecosim-v.2.1.7/ecosim.jar -d -s=reduced_further_core_mauve_aln_cat_maffted_trim.fa -p=reduced_further_core_mauve_aln_cat_maffted_trim_FastTree.tre -n -t=64` and the path to hillclimbing is exported. Do you have any idea of what might be going wrong? 

```
Ecotype Simulation 2.1.7

Opening sequence file...
  sequence length: 2,589,166.
  1 is the outgroup.
Opening tree file...
  39 environmental sequences.
  0.95 diversity sampled.
Running binning...
The result from binning:
  0.800: 1
  0.810: 1
  0.820: 1
  0.830: 1
  0.840: 1
  0.850: 1
  0.860: 1
  0.870: 1
  0.880: 1
  0.890: 1
  0.900: 1
  0.910: 1
  0.920: 1
  0.930: 1
  0.940: 1
  0.950: 3
  0.955: 8
  0.960: 8
  0.965: 9
  0.970: 10
  0.975: 10
  0.980: 11
  0.981: 11
  0.982: 11
  0.983: 11
  0.984: 11
  0.985: 11
  0.986: 11
  0.987: 11
  0.988: 11
  0.989: 11
  0.990: 12
  0.991: 12
  0.992: 13
  0.993: 15
  0.994: 16
  0.995: 20
  0.996: 23
  0.997: 27
  0.998: 28
  0.999: 29
  1.000: 38

Running parameter estimate...
The estimated parameters:
  npop:        14
  omega:       0.0000
  sigma:       0.0001

Running hillclimbing...
Starting with precision: 1.50x
Program hillclimb is not executable or was not found!
Error reading the output file.
Exception in thread "Thread-0" java.lang.NullPointerException
	at ecosim.Hillclimb.run(Hillclimb.java:83)
	at ecosim.Simulation.runHillclimbing(Simulation.java:458)
	at ecosim.EcotypeSimulation.run(EcotypeSimulation.java:221)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by isidoramorel** [comment]
I managed to run it :) The alignment and tree needed to be in the parent directory of the bin directory :)

**Comment by sandain** [comment]
I'm glad you figured it out!
